### ISSUE TITLE
Cannot add weather station

### ISSUE THREAD

**Issue by Muyz** [athombv/com.netatmo#1]
This is all I see when I try to add my weather station to Homey:

![schermafbeelding 2016-02-10 om 17 38 25](https://cloud.githubusercontent.com/assets/17163901/12954109/858d7e08-d01d-11e5-9c80-69ff3b8b178b.png)

**Comment by WeeJeWel** [comment]
Is there a pop-up being blocked?

**Comment by Muyz** [comment]
Nope, doesn't look like it:
![schermafbeelding 2016-02-10 om 18 13 21](https://cloud.githubusercontent.com/assets/17163901/12955171/1958a5d2-d022-11e5-8ef2-0962105f0f2a.png)

**Comment by WeeJeWel** [comment]
Alright. Could you show the console output? (Right click somewhere, Inspect Element, tab Console)  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by Muyz** [comment]
After some time, this appears in the console:

![schermafbeelding 2016-02-10 om 18 22 20](https://cloud.githubusercontent.com/assets/17163901/12955430/4a6b086c-d023-11e5-8f83-d5b750dddac4.png)

**Comment by JohanvanZanten** [comment]
Hi Emile

I have the same issue, 
![image](https://cloud.githubusercontent.com/assets/17182576/12984863/12c8ca84-d0f0-11e5-85b2-1f3992239f31.png)

**Comment by petergab94** [comment]
I have the same issue,
![image](https://cloud.githubusercontent.com/assets/17183593/13001379/88cd27c8-d165-11e5-9a25-7f630b29317e.png)

**Comment by ktbken** [comment]
I am getting the same issue. 
I have tried safari , firefox and chrome all on OS X and all will eventually give the same error as stated above

**Comment by WeeJeWel** [comment]
The NetAtmo app has been updated and is working again!

**Comment by ktbken** [comment]
Nice try and thanks for quick response,  but just getting a continual spinning gear now on the login page now

**Comment by WeeJeWel** [comment]
It can take a while for the popup to appear. Is Homey connected to my.athom.com?

**Comment by ktbken** [comment]
Yes it is 
I am still getting same errors in log
[](http://grab.by/O5AA)

**Comment by WeeJeWel** [comment]
Have you actually updated the app?

**Comment by ktbken** [comment]
Yes i actually uninstalled it and reinstalled now on 1.0.3

**Comment by WeeJeWel** [comment]
Hm OK. Please update to Homey 0.8.18 when it's available (few days) and report back.

**Comment by ktbken** [comment]
ok np

**Comment by SimNL** [comment]
In version 0.8.20 I'm still having this issue. I also tried reinstalling the app, but that didn't work.

**Comment by Muyz** [comment]
Same here: in 0.8.20 the gear wheel keeps spinning when trying to log into my Netatmo account.

**Comment by WeeJeWel** [comment]
Please update the app and try again.

**Comment by Muyz** [comment]
Removed app, rebooted Homey, installed v1.0.4 of the app. Issue persists.

**Comment by WeeJeWel** [comment]
Aw crap. Can you make a screencast of the pairing?

**Comment by Muyz** [comment]
You mean like this? :
![screen shot 2016-02-25 at 22 13 49](https://cloud.githubusercontent.com/assets/17163901/13334602/1434a384-dc0d-11e5-95ba-44291eb64d8c.png)

**Comment by WeeJeWel** [comment]
Yes but animated and the whole browser visible (preferably with a console open)  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by Muyz** [comment]
This is it: nothing more appears in console (left it open for a while):
![screen shot 2016-02-25 at 22 22 47](https://cloud.githubusercontent.com/assets/17163901/13334866/63f83cfe-dc0e-11e5-8c26-b3fd829d0977.png)

**Comment by Dijker** [comment]
Same here, 
tried with most Chrome extentions disabled in a incognito window and changed some other settings.
still not able to add my NetAtmo ;(

![image](https://cloud.githubusercontent.com/assets/12412734/13365436/41f72760-dcd5-11e5-84ff-311217f9d1f2.png)

**Comment by petergab94** [comment]
This is it: rien de plus apparaît dans la console (à gauche ouverte pendant
un certain temps):

2016-02-26 22:07 GMT+01:00 Dijker <notifications@github.com>:

**Comment by WeeJeWel** [comment]
I still cannot reproduce this issue (and don't speak french).

Is someone willing to invite me access to their station? Maybe that is where the issue lies.

**Comment by Dijker** [comment]
Ok Emile, You  have mail at your Gmail. 
Hope to hear from you.

**Comment by petergab94** [comment]
Good Job Emile,

connect ok,


but you can not select devices, I own 3 devices , 2 indoor and 1 outdoor .

good day !


2016-02-28 18:11 GMT+01:00 Emile Nijssen <notifications@github.com>:

**Comment by WeeJeWel** [comment]
Do you get a device at all?

**Comment by petergab94** [comment]
yes each device return :tempeture ..pressure ..  co2 ..and more noise .

2016-02-29 14:27 GMT+01:00 Emile Nijssen <notifications@github.com>:

**Comment by filoor** [comment]
@WeeJeWel  can you reopen it because my has stil the same problem

**Comment by WeeJeWel** [comment]
@filoor Is this issue still here with the newest version?

**Comment by filoor** [comment]
no not any more

**Comment by freemann** [comment]
Think this problem is not totally solved.
