### ISSUE TITLE
Triggers do not work

### ISSUE THREAD

**Issue by jeroenvano** [athombv/com.netatmo#12]
When using Netatmo app triggers the flows do not get executed anylonger.
Example when Noise has changed and is below 36dB then ....
Also testing flows does not work.

Netatmo v2.0.2. and Homey Firmware Version: 0.9.1

**Comment by BasKiers** [comment]
Hi, sorry for the very late reaction but this issue was never closed. If I am correct this issue was fixed some time ago so I will close the issue. Please open a new issue here or at github.com/athombv/homey/issues if you encounter more issues.
