### ISSUE TITLE
No longer showing data after Homey reboot

### ISSUE THREAD

**Issue by Veldkornet** [athombv/com.netatmo#15]
Initially the app was working fine however after rebooting Homey, I no longer receive any data on any of the stations. I've tried restarting the app itself but I have the same result

**Comment by Veldkornet** [comment]
FYI, I actually resolved my issue. 

I tried to "add" a new Netatmo device, and I was asked to re-authenticate. After this, the devices started working again. 

Nevertheless, I assume that this is not how the app should be working.

**Comment by caseda** [comment]
sometimes netatmo does require a "re-login" to make sure the account isn't used for things that shouldn't be used for.

bas has added a message now whenever that happens,
shouldn't happen too much though as it is only activated when netatmo thinks something fishy is going on (a lot of requesting data from the same ip for example)

**Comment by BasKiers** [comment]
Hi,

We published a rewrite as "beta" in the app store. We think this fixes most bugs and also adds support for the netatmo welcome and the home coach.

Regards,
Bas
