### ISSUE TITLE
Missing 2 rain sensor readings in device and variables 

### ISSUE THREAD

**Issue by jeroenvano** [athombv/com.netatmo#16]
Currently the app only supports the "Rain" sensor reading.
Netatmo also supports the variables "sum_rain_24" and "sum_rain_1" that the app does not support today.  

It would be nice if both variables get included into the app so we can use the readings in our flows and insights.

Regards,
Jeroen

**Comment by chrisboer** [comment]
Indeed I have the same request, rain sensor is only showing 0 value and with the summer coming I would like to create some flows to automatically water the garden.

**Comment by caseda** [comment]
i just entered the last testing fase for the rain meters...
just hope it will start raining soon/today (tuesday) so i can finalize the app for this. (if the triggers work)

Also will include battery levels.

**Comment by jeroenvano** [comment]
Thanks for adding mm/hour and cumulated today rain meters - appreciate the effort!
It seems that the cumulated today rain meter does not trigger on changes.

**Comment by caseda** [comment]
And you already re paired the rain sensor, like its being told in the Readme?

**Comment by jeroenvano** [comment]
Yes of course I did

Op 23 jun. 2017 10:17 schreef "R Mengers" <notifications@github.com>:

**Comment by caseda** [comment]
ok, i found the issue, and fixed it. (i made a change in the trigger id's i guess didn't pay enough attention to change them all)

though i also needed to add a bit of "protection" cause it also triggered when the app started :p that shouldn't happen.

expect it soon 😄 sorry for the inconvenience

**Comment by caseda** [comment]
fix is awaiting for bas to be accepted into the app 😄

you can of course side load, but you will have to use your own environmental file, unless you already know how, think it is easier to just wait until it is accepted

**Comment by caseda** [comment]
fix is in the latest update, tested a lot these last past days... little bit too much that i got but annoyed by every change 😛

**Comment by WoutervdBrink** [comment]
@caseda confirmed that this issue can now be closed 😄
