### ISSUE TITLE
[Request] Add support for Healthy Home Coach

### ISSUE THREAD

**Issue by SkorpionNL** [athombv/com.netatmo#17]
I would be very pleased if the Netatmo app can be extended with support for the Healthy Home Coach.

Netatmo has a reference available on their Dev website:

https://dev.netatmo.com/resources/technical/reference/healthyhomecoach/gethomecoachsdata

**Comment by WoutervdBrink** [comment]
Hi SkorpionNL, thank you for your feature request!

Unfortunately we do not have a Healthy Home Coach at the office. If you'd like, I can add the device according to the API specs and release the device support as an alpha version, letting you test it. Would you please let me know if this is an adequate solution?

**Comment by SkorpionNL** [comment]
Yes please, that would be great!

**Comment by WoutervdBrink** [comment]
I (think I)'ve sent you a message on Slack; find me there and we can set it up 😄

**Comment by jolny** [comment]
Hi guys, did you ever get around to solving this?
If not, I have the Home Coach and may be able to test.

**Comment by SkorpionNL** [comment]
Hi @jolny,

I gave @WoutervdBrink access to my HHC a while ago, and Wouter built support for it. Unfortunately the app is still in testing phase because Wouter is very busy with his study. I hope he can find the time anytime soon to finish the last pieces.

**Comment by WoutervdBrink** [comment]
Hi @SkorpionNL, @jolny: unfortunately, because of the mentioned study, I've had to quit my job at Athom a few months back.

As for the HHC support: I've indeed developed (some) support for that, and my friends at Athom should have the code. Seeing as I'm not an employee anymore, unfortunately I cannot give you any info on if and when that code will be used, but maybe @WeeJeWel or @BasKiers could tell you something about that :).

Hope this helps!
Wouter

**Comment by SkorpionNL** [comment]
Hi @WoutervdBrink,

Thanks for your reply and the work done so far! 

@WeeJeWel @BasKiers, Is it possible for you (or someone else on the team) to pick up the development for the Healthy Home Coach support?

**Comment by WeeJeWel** [comment]
Yes, we plan to add support, but it's not very high on our priority list at the moment so it could take a while!

**Comment by SkorpionNL** [comment]
Ok, Thx for the reply @WeeJeWel.

**Comment by BasKiers** [comment]
Hi,

We published a new version of the app as "beta" in the app store. We think this fixes most bugs and also adds support for the netatmo welcome and the home coach.

Regards,
Bas

**Comment by jolny** [comment]
@BasKiers thanks!
Tested it now, I select "Home coach", it logs in fine to Netatmo, but after that I get to select a device and only "Undefined" shows up. After adding it and clicking the Details-button (top left) it shows that small popup window but only a spinning wheel. :)

**Comment by BasKiers** [comment]
Hi,

I do not have access to a Home Coach so am unable to test. I will look into the issue you are describing. If you don't mind it could help me a lot if you could temporarily add my account to your home coach for testing. My Netatmo account email is bas@athom.nl.

Regards,
Bas

**Comment by SkorpionNL** [comment]
Sent you an invite for access to my HHC @BasKiers.

**Comment by BasKiers** [comment]
Hi,

Thanks a lot. I found the issue with the help of testing your device!
The healthy home coach should now work correctly.

Regards,
Bas

**Comment by SkorpionNL** [comment]
Hoi Bas,

Super! Het werkt top.

Bedankt voor de snelle fix!

Groet,
Jesper

2018-01-23 20:48 GMT+01:00 Bas Kiers <notifications@github.com>:
