### ISSUE TITLE
New Install NetAtmo pairing not started from Homey v1.5.0-RCx

### ISSUE THREAD

**Issue by Dijker** [athombv/com.netatmo#20]
Removed  NetAtmo, 
Added App v2.1.1 again to Homey 1.5.0-RC4
( Paring worked before in version< 1.4 and Pared App did work in 1.5.0 rc4)
Started Add Device:
See Chrome Console Errors:
(Don't know is it Homey Related or App?)

![image](https://user-images.githubusercontent.com/12412734/29098427-9abfb928-7c9f-11e7-86e6-5bc4cc023a5e.png)

VM228:89 Blocked opening 'https://callback.athom.com/oauth2/?token=******************************4&url=https%3A%2F%2Fapi.netatmo.net%2Foauth2%2Fauthorize%3Fresponse_type%3Dcode%26client_id%3*******e%26REDIRECT_URI%3Dhttps%3A%2F%2Fcallback.athom.com%2Foauth2%2Fcallback%2F%26scope%3Dread_station%2520read_thermostat%2520write_thermostat' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.
openAuthPopup @ VM228:89
(anonymous) @ VM228:8
(anonymous) @ homey.drivers.js:1
Homey._onPairMessage @ homey.drivers.js:1
(anonymous) @ crossframe.js:1
CrossFrame._onMessage @ crossframe.js:1
postMessage (async)
CrossFrame._post @ crossframe.js:1
CrossFrame.emit @ crossframe.js:1
proxyMessage @ devices.js:1
onPairMessage @ devices.js:1
Emitter.emit @ socket.io.js:1647
Socket.onevent @ socket.io.js:943
Socket.onpacket @ socket.io.js:901
(anonymous) @ socket.io.js:1512
Emitter.emit @ socket.io.js:1647
Manager.ondecoded @ socket.io.js:428
(anonymous) @ socket.io.js:1512
Emitter.emit @ socket.io.js:4389
Decoder.add @ socket.io.js:6740
Manager.ondata @ socket.io.js:418
(anonymous) @ socket.io.js:1512
Emitter.emit @ socket.io.js:4389
Socket.onPacket @ socket.io.js:2514
(anonymous) @ socket.io.js:2331
Emitter.emit @ socket.io.js:4389
Transport.onPacket @ socket.io.js:2947
Transport.onData @ socket.io.js:2939
ws.onmessage @ socket.io.js:4058
VM228:94 Uncaught TypeError: Cannot read property 'focus' of null
    at openAuthPopup (eval at globalEval (jquery.js:1), <anonymous>:94:4)
    at Function.eval (eval at globalEval (jquery.js:1), <anonymous>:8:5)
    at homey.drivers.js:1
    at Array.forEach (<anonymous>)
    at Homey._onPairMessage (homey.drivers.js:1)
    at crossframe.js:1
    at Array.forEach (<anonymous>)
    at CrossFrame._onMessage (crossframe.js:1)

**Comment by bvdbos** [comment]
https://googlechrome.github.io/samples/allow-popups-to-escape-sandbox/

**Comment by Dijker** [comment]
@bvdbos Is this something for the user to do in chrome? 
Didn't have a Homey desktop app to test last night but I guess it is also a problem from the app,
I think the change in 1.5 also needs an update in the NetAtmo app?

**Comment by bvdbos** [comment]
seeing this, it's Homey-core I think:
`
<iframe id="red" src="iframe.html"></iframe>


<iframe id="green" src="iframe.html" sandbox="allow-popups"></iframe>


<iframe id="blue" src="iframe.html"
        sandbox="allow-popups allow-popups-to-escape-sandbox"></iframe>`

**Comment by 2benl** [comment]
Same problem here. More people complaining in the app store.

**Comment by Dijker** [comment]
Workaround: 
using the pair Wizard on Chrome (on Windows) open the Developer Tools (Ctrl-Shift-I) and klik the blocked link in the console after adding a new Account. Authorize and switch back to the Homey Pair wizard. 
It works almost as normal. with except to the blocked link ;-)

**Comment by jeroenvollenbrock** [comment]
This is an app issue, apps should use Homey.popup instead of window.open

**Comment by Dijker** [comment]
Nice! I guess the impact is small for the official Athom Published apps:

https://github.com/search?q=org%3Aathombv+%22window.open%22&type=Code&utf8=%E2%9C%93

2x NetAtmo, maybe com.slack,  com.github and com.nest ? 

I tested com.ifttt but that one still works ;-) 
I will re-test when the update is available!

**Comment by 2benl** [comment]
I just installed the Github version with SDK2 changes, but when I try to add my weatherstation the pop-up closes with this error in Chrome:

Ignored call to 'alert()'. The document is sandboxed, and the 'allow-modals' keyword is not set.
(anonymous) @ VM351:105
(anonymous) @ homey.drivers.js:1
Homey._onPairMessage @ homey.drivers.js:1
(anonymous) @ crossframe.js:1
CrossFrame._onMessage @ crossframe.js:1
postMessage (async)
CrossFrame._post @ crossframe.js:1
CrossFrame.emit @ crossframe.js:1
proxyMessage @ devices.js:1
onPairMessage @ devices.js:1
Emitter.emit @ socket.io.js:1647
Socket.onevent @ socket.io.js:943
Socket.onpacket @ socket.io.js:901
(anonymous) @ socket.io.js:1512
Emitter.emit @ socket.io.js:1647
Manager.ondecoded @ socket.io.js:428
(anonymous) @ socket.io.js:1512
Emitter.emit @ socket.io.js:4389
Decoder.add @ socket.io.js:6740
Manager.ondata @ socket.io.js:418
(anonymous) @ socket.io.js:1512
Emitter.emit @ socket.io.js:4389
Socket.onPacket @ socket.io.js:2514
(anonymous) @ socket.io.js:2331
Emitter.emit @ socket.io.js:4389
Transport.onPacket @ socket.io.js:2947
Transport.onData @ socket.io.js:2939
ws.onmessage @ socket.io.js:4058

**Comment by Dijker** [comment]
@2benl 
Guess they didn't publish in the store if it isn't fully tested. 

did you add your own API key in env.json?
the pairing Pop-up works for me, but I get an other error after confirming the acces to NetAtmo (now including Welcome! )

moduleCapabilities is not defined
You may close this window.

We have to Wait until Athom releases it!

**Comment by WoutervdBrink** [comment]
We're currently working on a SDKv2 rewrite of the NetAtmo app. We've pushed some changes for this to master, resulting in the master branch not resulting in working, tested app.

We'll move our current efforts to another branch and revert the master branch. We'll also fix the smaller issue in the SDKv1 app mentioned above, in order to keep the SDKv1 version working.

The SDKv1 app supports most devices, except for the Welcome. The Welcome requires image tokens, which are only available in SDKv2, so that's why we're "migrating".

**Comment by 2benl** [comment]
Thnx for the quick response and the fast action!

**Comment by WoutervdBrink** [comment]
No problem! I've currently moved the SDKv2 rewrite to another branch.

Unfortunately, I cannot test code on a Homey at the moment, as I'm at home, so I'm unable to fix the issue mentioned here with `Homey.popup` until I'm back at the office on Monday. I'm sorry about that.

**Comment by 2benl** [comment]
You don't have a Homey @ home? 👎 

No problem off course, it's weekend. Njoy.

**Comment by Dijker** [comment]
@2benl I guess he has a Girlfriend, if he is wise he runs only stable at home ;-)

**Comment by Dijker** [comment]
@2benl  if you install the 2.1.1 from the app store AND the NetAtmo API is up .... you should be able to do the Workaround trick above imho ....
