### ISSUE TITLE
Reconnect to api.netatmo.net after url down

### ISSUE THREAD

**Issue by j0o5t** [athombv/com.netatmo#22]
I'm not sure if this can be solved in the plugin:

Lately api.netatmo.net seems to be down a lot. At first i deleted al of my Netatmo's causing me to lose all statistics ofcourse. Then  i found out that the website was inaccesable (duh). It seems the plugin won't reconnect to the website automaticly, re-authentication does not work, but a reboot after the url is available again works lik e a charm. I also launched a ticket at Netatmo for the availability of api.netatmo.net.

**Comment by WoutervdBrink** [comment]
Thanks for your issue report! We're currently working on a rewrite of the app to the apps SDK v2. I'm assigned to do this; I'll look into your issue while working on it and see if I can diagnose and / or fix it.

**Comment by j0o5t** [comment]
Tnx!
Netatmo stated that they had some issues with the api portal, but that should be fixed now and won't happen anymore. They closed my ticket.

**Comment by BasKiers** [comment]
Hi,

We published the rewrite as "beta" in the app store. We think this fixes most bugs and also adds support for the netatmo welcome and the home coach.

Regards,
Bas
