### ISSUE TITLE
Error adding Netatmo device using wizard

### ISSUE THREAD

**Issue by DavidDjerf** [athombv/com.netatmo#27]
I noticed that the Netatmo devices in Homey had old data, but even with a restart it would not update.
After switching to the beta version of the Netatmo App, I tried to add a new device, because that was what the info told me to do (please re-pair this device).
After I have approved the app in the Netatmo popup, I get a "window" with [object Object] and nothing happens. 
![netatmo-error-jpg](https://user-images.githubusercontent.com/39162087/41797341-f69f1756-7669-11e8-83f7-b825c85c9b53.JPG)

**Comment by Erik-Lam** [comment]
I have the same problem. Created an issue here: https://github.com/athombv/homey/issues/2516

**Comment by jeroenvollenbrock** [comment]
Closing as duplicate of athombv/homey#2516
