### ISSUE TITLE
NetAtmo outside module and additional Modules measurements

### ISSUE THREAD

**Issue by Dijker** [athombv/com.netatmo#4]
**What is your Homey / App version (Settings → System)?**
Version 0.8.24 / NetAtmo 1.0.7.
**What did you try to achieve?**
Read the outside Temperature, Humidity and Rain

*Please include detailed steps how we can reproduce the issue*
Every base station comes with an outside module, it reports Outside-Temperature and Humidity. 
I also have a additional inside module and a Rain Gauge.

I Installed the App, Added the module, go to Insights dashboard of Homey.

**What was the result?**
I can read the inside Temperature, Humidity, CO2 Pressure and Noise.

**What did you expect as result?**
Insight graphs for default module:
- outside Temperature, Humidity;
Insight graphs for additional modules:
- up to three additional modules Temperature, Humidity, CO2
- measured Rain. And maybe accumulated per hour or day. 

**Any other remarks**
still wondering how to read the cryptic language in driver.js ;-)

**Comment by BasPost** [comment]
When will this app be updated? And add the extra modules?
Also the new wind gauge

**Comment by freemann** [comment]
Just did a pull request to add support for modules.

https://github.com/athombv/com.netatmo/pull/7
