### ISSUE TITLE
Login screen does not work

### ISSUE THREAD

**Issue by Tweake** [athombv/com.netatmo#5]
![screenshot from 2016-04-20 14 13 15](https://cloud.githubusercontent.com/assets/10051731/14674150/c804c9dc-0702-11e6-969d-b3644f5a2812.png)

After clicking add device, nothing happens except the loading icon in the screenshot above

**Comment by freemann** [comment]
here also.

Found that "Homey.env" is "{}" and probably a incomplete/incorrect url is generated where Homey.env.CLIENT_ID = "undefined"
